#if !defined(AFX_IMGSCAN_H__3CAF1DDF_08EF_4462_8941_0C2F0B729EE1__INCLUDED_)
#define AFX_IMGSCAN_H__3CAF1DDF_08EF_4462_8941_0C2F0B729EE1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CImgScan wrapper class

class CImgScan : public CWnd
{
protected:
	DECLARE_DYNCREATE(CImgScan)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x84926ca0, 0x2941, 0x101c, { 0x81, 0x6f, 0xe, 0x60, 0x13, 0x11, 0x4b, 0x7f } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetImage();
	void SetImage(LPCTSTR);
	CString GetDestImageControl();
	void SetDestImageControl(LPCTSTR);
	BOOL GetScroll();
	void SetScroll(BOOL);
	BOOL GetStopScanBox();
	void SetStopScanBox(BOOL);
	long GetPage();
	void SetPage(long);
	long GetPageOption();
	void SetPageOption(long);
	long GetPageCount();
	void SetPageCount(long);
	long GetStatusCode();
	void SetStatusCode(long);
	long GetFileType();
	void SetFileType(long);
	BOOL GetMultiPage();
	void SetMultiPage(BOOL);
	long GetScanTo();
	void SetScanTo(long);
	float GetZoom();
	void SetZoom(float);
	BOOL GetShowSetupBeforeScan();
	void SetShowSetupBeforeScan(BOOL);

// Operations
public:
	long OpenScanner();
	long StartScan();
	long CloseScanner();
	BOOL ScannerAvailable();
	long ShowSelectScanner();
	long StopScan();
	long ShowScanNew(const VARIANT& Modal);
	long ShowScanPage(const VARIANT& Modal);
	CString GetVersion();
	long ShowScanPreferences();
	long GetPageTypeCompressionType(long ImageType);
	long GetPageTypeCompressionInfo(long ImageType);
	long GetCompressionPreference();
	short SetPageTypeCompressionOpts(long CompPref, long ImageType, long CompType, long CompInfo);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IMGSCAN_H__3CAF1DDF_08EF_4462_8941_0C2F0B729EE1__INCLUDED_)
