#if !defined(AFX_GIF_H__8FCB1E3D_A4BF_4BDD_8D4B_DD3E3E15AC5F__INCLUDED_)
#define AFX_GIF_H__8FCB1E3D_A4BF_4BDD_8D4B_DD3E3E15AC5F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CGIF wrapper class

class CGIF : public CWnd
{
protected:
	DECLARE_DYNCREATE(CGIF)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x832be334, 0xca39, 0x4f64, { 0x99, 0x88, 0xe4, 0x3c, 0x15, 0x96, 0xa9, 0xac } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL GetCancel();
	void SetCancel(BOOL bNewValue);
	CString GetCaption();
	void SetCaption(LPCTSTR lpszNewValue);
	BOOL GetDefault();
	void SetDefault(BOOL bNewValue);
	short GetDragCursor();
	void SetDragCursor(short nNewValue);
	long GetDragMode();
	void SetDragMode(long nNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	COleFont GetFont();
	void SetFont(LPDISPATCH newValue);
	void SetRefFont(LPDISPATCH* newValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	BOOL GetWordWrap();
	void SetWordWrap(BOOL bNewValue);
	long DrawTextBiDiModeFlagsReadingOnly();
	void InitiateAction();
	BOOL IsRightToLeft();
	BOOL UseRightToLeftReading();
	BOOL UseRightToLeftScrollBar();
	void SetSubComponent(BOOL IsSubComponent);
	void SaveToFile(LPCTSTR FileName);
	CString GetBmpFile();
	void SetBmpFile(LPCTSTR lpszNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GIF_H__8FCB1E3D_A4BF_4BDD_8D4B_DD3E3E15AC5F__INCLUDED_)
