#if !defined(AFX_JPG_H__D75D07B3_C62B_48C3_AD27_37D70E1A1598__INCLUDED_)
#define AFX_JPG_H__D75D07B3_C62B_48C3_AD27_37D70E1A1598__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CJPG wrapper class

class CJPG : public CWnd
{
protected:
	DECLARE_DYNCREATE(CJPG)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x662ca9d6, 0xa177, 0x44d4, { 0xa7, 0xba, 0xe6, 0xe4, 0x77, 0xc9, 0x5a, 0x39 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL GetCancel();
	void SetCancel(BOOL bNewValue);
	CString GetCaption();
	void SetCaption(LPCTSTR lpszNewValue);
	BOOL GetDefault();
	void SetDefault(BOOL bNewValue);
	short GetDragCursor();
	void SetDragCursor(short nNewValue);
	long GetDragMode();
	void SetDragMode(long nNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	COleFont GetFont();
	void SetFont(LPDISPATCH newValue);
	void SetRefFont(LPDISPATCH* newValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	BOOL GetWordWrap();
	void SetWordWrap(BOOL bNewValue);
	long DrawTextBiDiModeFlagsReadingOnly();
	void InitiateAction();
	BOOL IsRightToLeft();
	BOOL UseRightToLeftReading();
	BOOL UseRightToLeftScrollBar();
	void SetSubComponent(BOOL IsSubComponent);
	CString GetBmpFile();
	void SetBmpFile(LPCTSTR lpszNewValue);
	long GetQuality();
	void SetQuality(long nNewValue);
	void BmpToJPG(LPCTSTR FileName);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_JPG_H__D75D07B3_C62B_48C3_AD27_37D70E1A1598__INCLUDED_)
